name: yt_update
description: "AppUpdate"
version: 0.0.2
homepage: https://github.com/yutaotao2822/AppUpdate.git

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.yt.update.yt_update
        pluginClass: YtUpdatePlugin
      ios:
        pluginClass: YtUpdatePlugin
